---
title: "Time Series"
author: "Kendall Brown"
date: "September 14, 2018"
output: pdf_document
---
```{r}
library(tseries)
```
```{r}
airpassengers=AirPassengers
summary(airpassengers)
plot(airpassengers)
boxplot(airpassengers~cycle(airpassengers))
```
Convert data to stationary
```{r}
airlog=log(airpassengers)
airdiff=diff(airlog)
plot(airdiff)
```
```{r}
adf.test(airdiff,alternative=c("stationary","explosive"),k=0)
```
```{r}
acf(airdiff)
pacf(airdiff)
```
```{r}
ts.fit=arima(airlog,c(0,1,1),seasonal = list(order=c(0,1,1),period=12))
pred=(predict(ts.fit,n.ahead=10*12))
pred1=exp(pred$pred)
```
```{r}
ts.plot(airpassengers,pred1,log="y",lty=c(1,3))
```
```{r}
datawide=ts(airpassengers,frequency = 12,start = c(1949,1),end=c(1959,12))
ts.fit2=arima(log(datawide),c(0,1,1),seasonal = list(order=c(0,1,1),period=12))
pred2=(predict(ts.fit,n.ahead=10*12))
pred3=exp(pred2$pred)
```
```{r}
data1=head(pred1,12)
predicted.1960=round(head(data1,12),0)
actual.1960=tail(airpassengers,12)
mean(predicted.1960/actual.1960)
predicted.1960=predicted.1960/1.09
as.integer(predicted.1960+.5)
actual.1960
as.integer(predicted.1960+.5)/actual.1960
```